config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "Simple AirBnB", flats_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add Flat", new_flat_path , class: "btn btn-primary" %>
      </li>
    </ul>
  </div>
</div>

<div class="container">
  <div class="card-deck">
    <% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
      <h5 class="card-title"><%= flat.name %></h5>
        <h6 class="card-subtitle"><%= flat.address %></h6>
        <div class="d-inline-flex">
          <div class="flex">
            <i class="fas fa-dollar-sign"></i>
            <span><%= flat.price_per_night %></span>
          </div>
          <div class="flex ml-3">
            <i class="fas fa-user-friends"></i>
            <span><%= flat.number_of_guests %></span>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to "More Info", flat_path(flat.id) %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>